from __future__ import annotations

from pathlib import Path
from typing import Any, Protocol


class DeviceDriver(Protocol):
    """Minimal cross-device contract used by mobile environments."""

    raw: Any

    def connect(self) -> None: ...

    def close(self) -> None: ...

    def get_info(self) -> dict[str, Any]: ...

    def current_app(self) -> dict[str, Any]: ...

    def launch_app(self, package: str, activity: str | None = None) -> None: ...

    def stop_app(self, package: str) -> None: ...

    def screenshot(self, path: Path) -> None: ...

    def dump_hierarchy(self) -> str: ...

    def click(self, x: int, y: int) -> None: ...

    def swipe(self, sx: int, sy: int, ex: int, ey: int, duration: float = 0.2) -> None: ...

    def press(self, key: str) -> None: ...

    def input_text(self, text: str) -> None: ...

    def wait_idle(self, timeout: float = 5.0) -> None: ...

    def snapshot_text(self, *, max_chars: int = 20000) -> str: ...
